/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    sumArrays
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_Main_sumArrays
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
